services:
  vaultwarden-ship:
    image: vaultwarden/server:latest
    ports: ["8223:80"]  # Fixed port - stable external service
    volumes: 
      - "./data/vaultwarden:/data"
    environment:
      - WEBSOCKET_ENABLED=true
    networks: 
      - pronunco-production
    restart: unless-stopped